author: Galvanize Inc. <foss@galvanize.com>
license: MIT
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJHYWx2YW5pemUiLCJpYXQiOjE2ODk4MDQwNDcsImp0aSI6IjE5MDM3ZmQzMGEzMzZiZjQ4YTY0MWI4ODExZTE4MmZjIiwiZXhwIjoxNjg5ODExMjQ3LCJkYXRhIjp7ImlkIjoxNjUyNDUsImVtYWlsIjoiaWFubWNpbnR5cmUxMkBob3RtYWlsLmNvbSJ9fQ.8srf3KWTGCopFE_E7SHutWtZKNo24RNB2RtKKUFnYoE6W5KMJ6r12i-w2cEgk-Zvq0oWnNLRwq1valAleMD0DA
